site_name: OSG Council Working Homepage
site_url: https://opensciencegrid.github.io/council
repo_url: https://github.com/opensciencegrid/council
theme: readthedocs

extra_css:
  - css/extra.css

pages:
- Home: 'index.md'
- By-Laws: 'OpenScienceGridBylaws.md'
- Membership: 'Members.md'
- Minutes:
  - '11 June 2013': 'minutes/June-11-2013.md'

markdown_extensions:
  - admonition
  - osg_markdown.colors

