site_name: OSG Council Working Homepage
site_url: https://opensciencegrid.org/council/
repo_url: https://github.com/opensciencegrid/council/
theme: 
  name: material
  custom_dir: theme-customizations

nav:
- Home: 'index.md'
- Membership: 'Members.md'
- Meetings: 'Meetings.md'

markdown_extensions:
  - admonition

