site_name: OSG Council Working Homepage
site_url: https://opensciencegrid.org/council/
repo_url: https://github.com/opensciencegrid/council/
theme: 
  name: material
  custom_dir: theme-customizations

pages:
- Home: 'index.md'
- By-Laws: 'OpenScienceGridBylaws.md'
- Membership: 'Members.md'
- Voting Procedures: 'OpenScienceGridConsortiumVotingProcedures.md'
- Management Plan: 'OpenScienceGridManagementPlan.md'
- Member Expectations: 'MemberExpectations.md'
- Action Items: 'CouncilActionItems.md'

markdown_extensions:
  - admonition
  - osg_markdown.colors

