site_name: OSG Council
site_url: https://osg-htc.org/council/
repo_url: https://github.com/osg-htc/council/
theme: 
  name: material
  custom_dir: theme-customizations

nav:
- Home: 'index.md'
- Membership: 'Members.md'
- Meetings: 'Meetings.md'

markdown_extensions:
  - admonition
